// <auto-generated />
using FtpExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace FtpExplorer.Data.Migrations
{
    [DbContext(typeof(PasswordContext))]
    [Migration("20180123033857_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("FtpExplorer.Data.Password", b =>
                {
                    b.Property<int>("PasswordId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("EncryptedPassword")
                        .IsRequired();

                    b.Property<string>("Host")
                        .IsRequired();

                    b.Property<int>("Port");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("PasswordId");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
