// <auto-generated />
using FtpExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FtpExplorer.Data.Migrations.History
{
    [DbContext(typeof(HistoryContext))]
    partial class HistoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("FtpExplorer.Data.HistoryEntry", b =>
                {
                    b.Property<int>("HistoryEntryId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("HistoryEntryId");

                    b.ToTable("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
